[book]
title = "Cepheus SRD"
authors = ["Jason \"Flynn\" Kemp"]
language = "pt-BR"
src = "src"

[output.html]
default-theme = "rust"
preferred-dark-theme = "rust"
mathjax-support = true
fold = { enable = true, level = 0 }
git-repository-url = "https://github.com/nerun/cepheus"

[build]
build-dir = "docs"
